### ISSUE TITLE
AMD Graphics Drivers

### ISSUE THREAD

**Issue by dinoocch** [collegiumv/cv_client_bleeding#9]
The graphics cards in the gaming side of the lounge are AMD Tahiti PRO cards.

    root@oberon:/home/cv# lspci -v -s 01:00.0
    \01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti PRO [Radeon HD 7950/8950 OEM / R9 280] (prog-if 00 [VGA controller])
    	Subsystem: Hightech Information System Ltd. Device 3000
    	Flags: bus master, fast devsel, latency 0, IRQ 46
    	Memory at e0000000 (64-bit, prefetchable) [size=256M]
    	Memory at f0000000 (64-bit, non-prefetchable) [size=256K]
    	I/O ports at e000 [size=256]
    	Expansion ROM at f0040000 [disabled] [size=128K]
    	Capabilities: [48] Vendor Specific Information: Len=08 <?>
    	Capabilities: [50] Power Management version 3
    	Capabilities: [58] Express Legacy Endpoint, MSI 00
    	Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
    	Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
    	Capabilities: [150] Advanced Error Reporting
    	Capabilities: [270] #19
    	Capabilities: [2b0] Address Translation Service (ATS)
    	Capabilities: [2c0] #13
    	Capabilities: [2d0] #1b
    	Kernel driver in use: radeon

We're using the free (open source) drivers (radeon).

However, it is possible/probable that the proprietary drivers will provide better performance and power management than this driver. (fglrx)

Since we already have the proprietary sources included (I'm reasonably sure on this...)
```
sudo apt-get install fglrx
```
or in the main.yml
```
- name: Install proprietary AMD drivers
  apt: name=fglrx install_recommends=yes state=present
```

There is another driver: fglrx-updates which includes updates after the stable freeze. However, there have been reports of some instability with unity...

**Comment by phy1729** [comment]
I think that [this line](https://github.com/phy1729/cv_config/blob/master/roles/preseed_site/files/preseed/firstBootClient.sh#L7) installs the correct proprietary driver; however, this is more of @the-maldridge's area of expertise.

**Comment by dinoocch** [comment]
AMD Proprietary drivers are specifically excluded from ubuntu-drivers autoinstall. :8ball:

**Comment by the-maldridge** [comment]
While this is a confirmed bug, it is low priority until such time as authentication is brought online.  The existing driver is perfectly functional and will be used until there is justifiable cause to replace it.
